
ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017006
 ENABLE;

ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017007
 ENABLE;


ALTER TABLE DTM_DEV.LOCATION
 MODIFY CONSTRAINT LOCATION_UQ01
 ENABLE;


ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017009
 ENABLE;