ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017006
 DISABLE;

ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017007
 DISABLE;

ALTER TABLE DTM_DEV.COMPANY
 MODIFY CONSTRAINT SYS_C0017009
 DISABLE;

ALTER TABLE DTM_DEV.LOCATION
 MODIFY CONSTRAINT LOCATION_UQ01
 DISABLE;